version: "3.9"

services:

  app:
    image: driving_accompany
    build: ./driving_accompany
    container_name: driving_accompany
    restart: always
    expose:
      - 5000

  nginx:
    image: nginx
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    